### ISSUE TITLE
Which paper is this GAN network based on?

### ISSUE THREAD

**Issue by aghanbar** [brajard/inpainting#22]
Can you cite the paper you built this model from? Thanks.

**Comment by brajard** [comment]
I add the reference
Be careful: this deposit is not up to date
Pathak, D., Krähenbühl, P., Donahue, J., Darrell, T., & Efros, A. A. (n.d.). Context Encoders: Feature Learning by Inpainting. Retrieved from http://people.eecs.berkeley.edu/~pathak/papers/cvpr16.pdf
